### ISSUE TITLE
(Issues) Overalay

### ISSUE THREAD

**Issue by glodar** [patriksletmo/Dota2Translator#8]
Cant see overlay even if i click on add overlay and its tab me in game and its not more clickble.
Tryed reinstalling all programs,runned as admin,cant change network adapter coz have just 1 on list even if i runed as admin.
Translation work just on program and im forced to alt-tab to see it.
Win Xp 32bit res in dota 1360 768...tryed runnin in fullscrean,window,and window bordless
alwyas same happed overlay looks like its added but i cant see.
Hopeing for fix : ( coz program is best ever maded for some game...and i cant have full expirience

**Comment by patriksletmo** [comment]
I did some work on indicating when the overlay had been added in patch 84d9ed2f42afd02874e78881d9a9d11c43adde2a. It will display a message in the game using the overlay, so it would be possible to see if this is a problem with the hooking or the communication between the hooked DLL and the program. I uploaded a build of my latest patches on Mega, could you test if the message shows?

Download the patch here https://mega.co.nz/#!019mTLBC!AWP-glM8atxjY90BndPs0QjD7x0HgOR4VvAwh4-jdAU, then paste the files included into the installation directory.
Example of the message http://i.imgur.com/6zUlZbJ.png

**Comment by glodar** [comment]
no msg still everthing is same...tab me in game but no msg that is added or translation in game...
thx for trying to help me..

**Comment by patriksletmo** [comment]
Okay, then it seems like there is not a problem with the communication - that's positive. I will Google for similar problems with EasyHook tomorrow, I'll make sure to keep you updated!

**Comment by patriksletmo** [comment]
New test build!
This time I added some debugging messages to see if the EndScene function was called and to see what addresses were hooked. It should look something like this http://i.imgur.com/JlReNnp.png

Note: The debugging functions in this build have not been optimized. Please don't use this for other purposes than debugging.
Download: https://mega.co.nz/#!B51lGS4a!I6ChASO20dhPdG4Lj7vH6TNqBdpLgmy_Ts9Ki4JXSoc

**Comment by glodar** [comment]
this is what i getting
http://oi49.tinypic.com/2wd4hzs.jpg
still have msg in program but no ingame

**Comment by patriksletmo** [comment]
Interesting, it seems like the injected DLL crashes during the hooking of the DirectX API. I changed the debugging part to also include the error message around this part, if you could try running a test with this patch I could probably fix the issue very quickly :)

Download https://mega.co.nz/#!NolHAYiZ!N1buJGpjUK1qtT1BnZzevDUpjWQ080DtdTWd7Py-Lr0

**Comment by glodar** [comment]
http://oi46.tinypic.com/1tabf5.jpg
hope ull find fix...amazing program i rly would like to use it

**Comment by patriksletmo** [comment]
Seems like your graphics card doesn't support some of the modes the dummy device uses to find the memory addresses of the hooks. This is nothing to worry about, I'll write a program that checks what modes your graphics card can handle when I get home again and then I'll see if I can replace the dummy device in order to keep the program working as well as supporting your hardware :)

**Comment by patriksletmo** [comment]
Okay, I just got home and wrote this application https://mega.co.nz/#!s49Wwb7R!cC1c2haVa66CDWpWs87Dr2U1IVlQ-ik9i295z49SQ5s

Could you tell me what tests succeeded and what failed?

**Comment by glodar** [comment]
i cant open that application..
getting this error C:\Program Files\Dota 2 Translator\SlimDXTestApplication.exe is not valid Win32 application

**Comment by glodar** [comment]
missclick with close and commant..

**Comment by patriksletmo** [comment]
Woops, my bad. Took an old build of it made for 64-bit.
Try this instead https://mega.co.nz/#!E49zgJ7A!T6MPyQyGw2A6SdAYi5ZgUUVI-QV3gRX4TeJvuaxE3Vk

**Comment by glodar** [comment]
same msg not valid win 32 app

**Comment by patriksletmo** [comment]
Looked over the settings and finally made it include the correct SlimDX dll, this should most probably work https://mega.co.nz/#!IskQQY5D!Du1Z7GToS1_7gsofKLKWRippFZd6X3zqjd2oNXu8DKQ

**Comment by glodar** [comment]
ye it worked : )
but it looks that everythhing failing for me...
http://oi48.tinypic.com/hu280p.jpg

**Comment by patriksletmo** [comment]
Okay, then you will have to do some further stuff to debug this. The following steps will tell exactly what's wrong with the compatibility with your hardware instead of showing the generic error that was shown before :) 
1. Download the DirectX SDK from here http://www.microsoft.com/en-us/download/details.aspx?id=6812
2. Start the DirectX Control Panel (image of where to find it) http://i.imgur.com/vBdht1B.png)
3. Select the options marked in this picture http://i.imgur.com/g0STI4P.png and click apply
4. Start the last version of the Dota 2 Translator that I sent you (not the debugging program called SlimDXTestApplication.exe)
5. Start Dota 2 and press the "Add Overlay" button
6. The console attached to the program _should_ have some detailed information, make sure that you capture all of it in your screenshot
7. Reset the settings that you changed in step 3 to ensure that your DirectX applications run as smooth as possible (the debugging version tends to slow down games a lot)

**Comment by glodar** [comment]
..it show me same like last capture i send u in post 7 http://tinypic.com/view.php?pic=1tabf5&s=6

**Comment by patriksletmo** [comment]
Turns out you have to download this program called DebugView http://technet.microsoft.com/en-us/sysinternals/bb896647 to see the necessary information.

Make sure that DirectX is in debug mode with the most debug output available. Then start DebugView, open the program and press "Add Overlay". After that you go back to DebugView and click save. You could upload the log or make a pastebin of it.

**Comment by glodar** [comment]
i couldnt make pastebin its too large..so here is link http://www.sendspace.com/file/yfndm0
also i try 2 time debug view coz 1st i was think to w8 till finish..but it was scrolling for 15 min...2nd time i saved after add overlay and that uploaded and debug view still was scroling till i close program

**Comment by patriksletmo** [comment]
That contains just what I wanted, thank you! Apparently some versions of DirectX wants a pointer to a window while creating a device. Could you try this patch and see if it works? It most probably should :) https://mega.co.nz/#!9hFBnRIa!J6ioNQmdi6UtqMyuqyuj8E4r5MovTzHac4EjpsPlZ3k

Also, don't forget to turn off debugging mode in the DirectX control panel before testing! The overlay won't show up otherwise.

**Comment by glodar** [comment]
i turned back everything changed on dxcontrolpanel but it same no overlay  not working...
sorry if this wasting ur time..

**Comment by patriksletmo** [comment]
No you're not wasting my time, I want to make sure that everyone can run this program :) 

I replaced the console with a log file, it's located in Appdata/Dota 2 Translator/log.txt. Could you check if it contains the same error message as before (invalid call)? If it does it would be quite handy if you re-ran the test with DebugView using the new patch to see if there's a any other error :)

**Comment by glodar** [comment]
i think its same msg anyway i upload that http://www.sendspace.com/file/hprjg2

and here is new debugview  http://www.sendspace.com/file/71fdjw

**Comment by patriksletmo** [comment]
Yah, the DebugView is the same too. I guess I misplaced the reading of the window handle, which would give the same result as passing a null window handle (which was done before). I'll make sure to fix it the first thing I do tomorrow morning!

**Comment by patriksletmo** [comment]
Turns out that was the problem. I guess I shouldn't be fixing bugs too early in the morning, heh. Anyway, here is the patch https://mega.co.nz/#!M981hADR!GQ0gDz6J9oQ6ZD450ls0fXab8WJ5RxqgBI6cVt7-6mw. It _should_ fix the problem, just make sure to run DirectX in normal mode.

**Comment by glodar** [comment]
everything working :))))))))))))) msg when overlay added and translation :) everything..
i dont have paypal to donate but ill try to find way to donate max i can coz u deserving 100%
ty so much
